apiVersion: v2
name: terminal-proxy
description: Helm chart for deploying the agyn Terminal Proxy service.
type: application
version: 0.1.0
appVersion: 0.6.1
home: https://github.com/agynio/terminal-proxy
sources:
  - https://github.com/agynio/terminal-proxy
dependencies:
  - name: service-base
    version: ">=0.1.4 <1.0.0"
    repository: oci://ghcr.io/agynio/charts
