{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.secretName" . }}
  labels:
{{ include "service-base.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.bootstrapPasswordKey }}: {{ .Values.auth.bootstrapPassword | quote }}
  {{ .Values.auth.adminPasswordKey }}: {{ .Values.auth.adminPassword | quote }}
  {{- if not .Values.database.existingSecret }}
  database-password: {{ .Values.database.password | quote }}
  {{- end }}
{{- end }}
