{{- if .Values.files.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agyn-platform.fullname" . }}-files
  labels:
    app.kubernetes.io/name: files
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
{{- end }}
